// Email service for sending invoices
import * as MailComposer from 'expo-mail-composer';
import * as Sharing from 'expo-sharing';
import { Invoice, AppSettings } from '../types';
import { getSettings, markInvoiceSent, updateInvoiceSentAt } from './database';
import { getCurrentTimestamp, getWeekRangeDisplay, formatMinutesToHHMM } from '../utils/dateUtils';

/**
 * Check if email is available on device
 */
export async function isEmailAvailable(): Promise<boolean> {
  return await MailComposer.isAvailableAsync();
}

/**
 * Check if sharing is available
 */
export async function isSharingAvailable(): Promise<boolean> {
  return await Sharing.isAvailableAsync();
}

/**
 * Send invoice via device email app (manual send)
 */
export async function sendInvoiceEmail(
  invoice: Invoice,
  weekStartDate: string
): Promise<{ success: boolean; error?: string }> {
  try {
    const settings = await getSettings();
    
    if (!settings?.recipientEmail) {
      return { success: false, error: 'No recipient email configured' };
    }
    
    // Use device email app
    const isAvailable = await isEmailAvailable();
    
    if (!isAvailable) {
      return { success: false, error: 'Email is not available on this device' };
    }
    
    const weekRange = getWeekRangeDisplay(weekStartDate);
    const totalTime = formatMinutesToHHMM(invoice.totalMinutes);
    const rate = settings.hourlyRate || 0;
    const subtotal = rate > 0 ? (invoice.totalMinutes / 60) * rate : 0;
    const gstAmount = subtotal * 0.10;
    const totalAmount = subtotal + gstAmount;
    
    // Compose email body
    let emailBody = `
Dear Customer,

Please find attached the demurrage invoice for the week of ${weekRange}.

SUMMARY:
---------
Total Demurrage Events: ${invoice.events.length}
Total Demurrage Time: ${totalTime}
`;

    if (rate > 0) {
      emailBody += `Rate per Hour: $${rate.toFixed(2)}
Subtotal: $${subtotal.toFixed(2)}
GST (10%): $${gstAmount.toFixed(2)}
Total (Inc. GST): $${totalAmount.toFixed(2)}
`;
    }

    emailBody += `
The attached invoice contains a detailed breakdown of all demurrage events with timestamps and locations.

This invoice was generated by Demurrage Tracker.

Best regards,
${settings.companyName || 'Demurrage Tracking System'}
`;

    const result = await MailComposer.composeAsync({
      recipients: [settings.recipientEmail],
      subject: `Demurrage Invoice - ${weekRange}`,
      body: emailBody,
      attachments: invoice.pdfPath ? [invoice.pdfPath] : [],
      isHtml: false,
    });
    
    if (result.status === MailComposer.MailComposerStatus.SENT) {
      // Mark invoice as sent
      const sentAt = getCurrentTimestamp();
      await updateInvoiceSentAt(invoice.id, sentAt);
      await markInvoiceSent(weekStartDate);
      
      return { success: true };
    } else if (result.status === MailComposer.MailComposerStatus.CANCELLED) {
      return { success: false, error: 'Email was cancelled by user' };
    } else {
      return { success: false, error: 'Email was not sent' };
    }
  } catch (error) {
    console.error('Error sending invoice email:', error);
    return { success: false, error: String(error) };
  }
}

/**
 * Share invoice file
 */
export async function shareInvoice(invoice: Invoice): Promise<{ success: boolean; error?: string }> {
  try {
    if (!invoice.pdfPath) {
      return { success: false, error: 'Invoice file not found' };
    }
    
    const isAvailable = await isSharingAvailable();
    
    if (!isAvailable) {
      return { success: false, error: 'Sharing is not available on this device' };
    }
    
    await Sharing.shareAsync(invoice.pdfPath, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share Demurrage Invoice',
    });
    
    return { success: true };
  } catch (error) {
    console.error('Error sharing invoice:', error);
    return { success: false, error: String(error) };
  }
}

/**
 * Send a test email to verify settings
 */
export async function sendTestEmail(recipientEmail: string): Promise<{ success: boolean; error?: string }> {
  try {
    const isAvailable = await isEmailAvailable();
    
    if (!isAvailable) {
      return { success: false, error: 'Email is not available on this device' };
    }
    
    const result = await MailComposer.composeAsync({
      recipients: [recipientEmail],
      subject: 'Demurrage Tracker - Test Email',
      body: `
This is a test email from Demurrage Tracker.

If you received this email, your email settings are configured correctly.

Weekly demurrage invoices will be sent to this address automatically.
      `,
      isHtml: false,
    });
    
    if (result.status === MailComposer.MailComposerStatus.SENT) {
      return { success: true };
    } else {
      return { success: false, error: 'Test email was not sent' };
    }
  } catch (error) {
    console.error('Error sending test email:', error);
    return { success: false, error: String(error) };
  }
}

/**
 * Generate email preview content
 */
export function generateEmailPreview(
  invoice: Invoice,
  weekStartDate: string,
  settings: AppSettings
): string {
  const weekRange = getWeekRangeDisplay(weekStartDate);
  const totalTime = formatMinutesToHHMM(invoice.totalMinutes);
  const rate = settings.hourlyRate || 0;
  const totalAmount = rate > 0 ? (invoice.totalMinutes / 60) * rate : 0;
  
  let preview = `To: ${settings.recipientEmail}
Subject: Demurrage Invoice - ${weekRange}

---

Dear Customer,

Please find attached the demurrage invoice for the week of ${weekRange}.

SUMMARY:
Total Demurrage Events: ${invoice.events.length}
Total Demurrage Time: ${totalTime}`;

  if (rate > 0) {
    preview += `
Rate per Hour: $${rate.toFixed(2)}
Total Amount: $${totalAmount.toFixed(2)}`;
  }

  preview += `

Best regards,
${settings.companyName || 'Demurrage Tracking System'}`;

  return preview;
}
